# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chisq_statistic <- function(observed_left, observed_right, k, n) {
    .Call('maxchisq_chisq_statistic', PACKAGE = 'maxchisq', observed_left, observed_right, k, n)
}

pmaxchisq_permutation_internal <- function(b, k, n, num_permutations, y, num_left, class_counts) {
    .Call('maxchisq_pmaxchisq_permutation_internal', PACKAGE = 'maxchisq', b, k, n, num_permutations, y, num_left, class_counts)
}

